dfs_orig:
	g++ -std=c++11 -O3 -o dfs_orig dfs_orig.cpp

dfs_stack:
	g++ -std=c++11 -O3 -o dfs_stack dfs_stack.cpp

dfs_edge:
	g++ -std=c++11 -O3 -o dfs_edge dfs_edge.cpp

debug_orig:
	g++ -std=c++11 -O3 dfs_orig.cpp

debug_stack:
	g++ -std=c++11 -O3 dfs_stack.cpp

clean:
	rm -rf dfs_stack dfs_orig dfs_edge
	rm -rf a.*
	rm -rf a.out.dSYM
