dfs_orig:
	g++ -std=c++11 -O3 -o dfs_orig dfs_orig.cpp

dfs_stack:
	g++ -std=c++11 -O3 -o dfs_stack dfs_stack.cpp

dfs_edge:
	g++ -std=c++11 -O3 -o dfs_edge dfs_edge.cpp

dfs_articulation_stack:
	g++ -std=c++11 -O3 -o dfs_articulation_stack dfs_articulation_stack.cpp

dfs_articulation_recursion:
	g++ -std=c++11 -O3 -o dfs_articulation_recursion dfs_articulation_recursion.cpp

dfs_bridge_recursion:
	g++ -std=c++11 -O3 -o dfs_bridge_recursion dfs_bridge_recursion.cpp

dfs_bridge_stack:
	g++ -std=c++11 -O3 -o dfs_bridge_stack dfs_bridge_stack.cpp

debug_orig:
	g++ -std=c++11 -O3 dfs_orig.cpp

debug_stack:
	g++ -std=c++11 -O3 dfs_stack.cpp

clean:
	rm -rf dfs_stack dfs_orig dfs_edge dfs_articulation_stack dfs_articulation_recursion
	rm -rf a.*
	rm -rf a.out.dSYM
